#
###Version, do not change!##
#Range: > 0
Version = 15

#Recruits Config:
[Recruits]
	#
	#Max Recruits in a Village Chunk to Spawn
	#	(takes effect after restart)
	#	default: 1
	#Range: 1 ~ 10
	MaxSpawnRecruitsInVillage = 1
	#
	#----Should Pillagers attack all Living----
	#	(takes effect after restart)
	#	default: true
	ShouldPillagersRaidNaturally = true
	#
	#----Should Pillagers can spawn with shield and sword and AI to use these----
	#	(takes effect after restart)
	#	default: true
	PillagerSpawnItems = true
	#
	#----Mount Whitelist----
	#	(takes effect after restart)
	#	ONLY Entities in this list can be mounted by a recruit, for example: ["minecraft:boat", "smallships:cog"]
	"Mount Whitelist" = ["minecraft:horse", "minecraft:llama", "minecraft:pig", "minecraft:boat", "minecraft:minecart", "smallships:cog", "smallships:brigg", "camels:camel"]
	#
	#----Currency----
	#	(takes effect after restart)
	#	The Item defined here, will be used to hire recruits. For example: ["minecraft:diamond"]
	RecruitCurrency = "minecraft:emerald"
	#
	#----Should Recruits Make Villager Huh? sound?----
	#	(takes effect after restart)
	#	default: true
	PlayVillagerAmbientSound = true
	#
	#----Should Recruits instead of Iron Golems spawn in Villages ----
	#	(takes effect after restart)
	#	default: true
	OverrideIronGolemSpawn = true
	#
	#----Target Blacklist----
	#	(takes effect after restart)
	#	Entities in this list won't be targeted at all, for example: ["minecraft:creeper", "minecraft:sheep"]
	"Target BlackList" = []
	#
	#----Should Vindicators can spawn with shield and sword and AI to use these----
	#	(takes effect after restart)
	#	default: true
	VindicatorSpawnItems = true
	#
	#----Should Recruits look like Villagers?----
	#	(takes effect after restart)
	#	default: false
	RecruitsLookLikeVillagers = true
	#
	#----Bowman start hand equipment ----
	#	(takes effect after restart)
	#	Items in this list will be equipped to a new spawned bowman, in this following order: ["main-hand", "off-hand" ]
	BowmanStartHandEquipment = ["minecraft:bow", ""]
	#
	#----Should Recruits spawn as Patrols in the world?----
	#	(takes effect after restart)
	#	default: true
	ShouldRecruitPatrolsSpawn = true
	#
	#----Recruit start hand equipment ----
	#	(takes effect after restart)
	#	Items in this list will be equipped to a new spawned recruit, in this following order: ["main-hand", "off-hand"]
	RecruitStartHandEquipment = ["minecraft:wooden_sword", ""]
	#
	#----Should Pillagers Spawn naturally ----
	#	(takes effect after restart)
	#	default: true
	PillagerSpawn = true
	#
	#----Should Neutral Recruits attack immediately enemy players that are placing or breaking blocks?----
	#	(takes effect after restart)
	#	default: true
	NeutralRecruitsBlockEvents = true
	#
	#Max amount a player can recruit
	#	(takes effect after restart)
	#	default: 64
	#Range: 1 ~ 1280
	MaxRecruitsForPlayer = 64
	#
	#The cost to create a team.
	#	(takes effect after restart)
	#	default: 32
	#Range: 1 ~ 200
	TeamCreationCost = 32
	#
	#----Shieldman start hand equipment ----
	#	(takes effect after restart)
	#	Items in this list will be equipped to a new spawned shieldman, in this following order: ["main-hand", "off-hand" ]
	ShieldmanStartHandEquipment = ["minecraft:wooden_axe", "minecraft:shield"]
	#
	#----Start armor ----
	#	(takes effect after restart)
	#	Items in this list will be equipped to a new spawned recruits, for example: ["head", "chest", "legs", "feet"]
	StartArmorList = ["minecraft:leather_helmet", "minecraft:leather_chestplate", "minecraft:leather_leggings", "minecraft:leather_boots"]
	#
	#----Should Pillagers do Friendlyfire ----
	#	(takes effect after restart)
	#	default: false
	PillagerFriendlyFire = false
	#
	#WIP: Max Assassins to buy from the Assassin Leader
	#	(takes effect after restart)
	#	default: 16
	#Range: 1 ~ 64
	MaxAssassinCount = 16
	#
	#----Should Aggressive Recruits attack immediately enemy players that are placing or breaking blocks?----
	#	(takes effect after restart)
	#	default: true
	AggroRecruitsBlockEvents = true
	#
	#----Should Recruits Name Tag Render for the owner----
	#	(takes effect after restart)
	#	default: true
	RenderNameTagforOwner = true
	#
	#Max XP a Recruit needs to Level Up
	#	(takes effect after restart)
	#	default: 250
	#Range: 50 ~ 10000
	RecruitsMaxXpForLevelUp = 250
	#
	#----Should Pillagers attack Monsters----
	#	(takes effect after restart)
	#	default: true
	PillagerAttackMonsters = true
	#
	#----Should Pillagers have increased Combat Range, so they can shoot from far away----
	#	(takes effect after restart)
	#	default: true
	PillagerIncreasedCombatRange = true
	#
	#----Should Monsters attack Pillagers----
	#	(takes effect after restart)
	#	default: true
	MonstersAttackPillagers = true
	#
	#Distance Recruits will start to follow its owner
	#	(takes effect after restart)
	#	default: 9.0
	#Range: 4.0 ~ 16.0
	RecruitFollowStartDistance = 9.0
	#
	#----Chance that a Recruit Patrol can spawn. (higher = higher chance to spawn)----
	#	(takes effect after restart)
	#	default: 15.0
	#Range: 0.0 ~ 100.0
	RecruitPatrolsSpawnChance = 15.0

